### ISSUE TITLE
gérer la physique

### ISSUE THREAD

**Issue by pierreh37** [utcoupe/Coupe2012#15]
voir avec newton

**Comment by trecouvr** [comment]
Finalement nous utiliserons pymunk

**Comment by mattgu74** [comment]
Vous en avez pas marre de changer de technologie ? :p

**Comment by mattgu74** [comment]
Et je réouvre le ticket parce que jusqu'a nouvel ordre la physique n'est pas géré !!!
(enfin le commentaire de tom dis juste que vous changez de tech, pas que c'est fini...)

**Comment by pierreh37** [comment]
sisi la physique est géré en 2D et ça marche tres bien dans le simu (à part le problème des pions qui rentres dans le robot)

**Comment by mattgu74** [comment]
Je croyais que tu allais faire de la 3D... Aurais-tu revu tes exigences à la baisse ?

**Comment by pierreh37** [comment]
il vaut mieux avoir un truc fonctionnel que ultime en plus on abandonne pas la 3D c'est juste repoussé ^^
