### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by mattgu74** [utcoupe/Coupe2012#16]
Tu pourrais mettre un makefile avec ton simu ?

**Comment by pierreh37** [comment]
c'est du boulot tu veut pas utiliser le .cbp plutot?

**Comment by mattgu74** [comment]
LoL quoi.... ya pas un script cpb2makefile  ? ^^

**Comment by pierreh37** [comment]
Bon ba c'est ta quette mat trouve le cbp2makefile et génère un makefile ^^

**Comment by mattgu74** [comment]
http://sourceforge.net/apps/mediawiki/cbp2make/index.php?title=Main_Page

Cadeau ^^

**Comment by trecouvr** [comment]
lol, bah fait le toi même du coup ^^

**Comment by trecouvr** [comment]
projet avec gamekitengine abandonné, passage à python3-pygame-pymunk

**Comment by mattgu74** [comment]
Ha le retour au python.... ça m'aurait étonné que Thomas ne plusoie pas le simulateur en python :p
