### ISSUE TITLE
Libifier le protocole (C <-> Client Irc Python)

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#36]

**Comment by XdoctorwhoZ** [comment]
La com a été libifié, en attente de validation par thomas.

**Comment by trecouvr** [comment]
Ca m'a l'air cool ;p, 
Pourrais tu mettre des majuscules à tes classes comManager -> ComManager.
Tu peux faire un dossier skeleton à côté de hokuyo et visio, qui contient clientIRC et driver, et dans driver un code minimaliste utilisant ton protocole, style une commande qui sqrt qui renvoie la racine du nombre en entrée

#define Q_SQRT       49

./skeleton
42+49
42+7.0

(le caractère de séparation est le '+' maintenant)
