### ISSUE TITLE
Adressage pc fix

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#37]
Enregistre le pc fix dans le réseau utcoupe (10.10.10.103)
Et aussi changer pour grosordi.cheuv.eu, l'adresse ip sur le réseau utc est 172.25.140.6

**Comment by apuyou** [comment]
J'ai changé grosordi.cheuv.eu, par contre faut peut être attendre jusqu'à 24h.

Pour l'ip dans le réseau utcoupe, il lui faudrait une carte wifi en fait vu que c'est un réseau wifi...
