### ISSUE TITLE
Ramasser objets d'une face d'un totem

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#38]
Créer une commande arduino qui ouvre les "balais" et les rabats pour engloutir une face de totem

2 x AX18

**Comment by qchateau** [comment]
Quels moteurs ? Ils ont un PIN déjà attitré ou pas encore ? C'est juste ouvrir puis fermer les balais avec un temps d'attente entre les deux ou c'est c'est plus complexe que ca ?

**Comment by trecouvr** [comment]
AX18 dans mes souvenirs (c'est pareil que des AX12 au niveau contrôle). Regarde le dossier /arduino/ax12 pour un exemple, ya les branchements dans le README je crois.

**Comment by qchateau** [comment]
OK j'ai regardé comment se servir des AX18, me reste deux trois questions :
- Faut-il pouvoir controler la vitesse de rotation des moteurs ? (je pense pas mais on sait jamais)
- Question algorithme, si je fais que ouvrir puis fermer les balais, ca ramassera les objets ou juste ca servira à rien ?
  Je veux dire, faut il ouvrir les balais, avancer le robot, fermer les balais ou les balais sont-ils fait de manière à ce qu'une simple ouverture/fermeture face au totem permette de ramasser les objets ? (en gros je fais un delay+envoi de status au serveur IRC entre ouverture et fermeture ou j'enchaine les deux ?)

**Comment by trecouvr** [comment]
Yop,

ça se discute, mais je pense que côté arduino on aura vraiment que le bas niveau, donc il faut juste ouvrir/fermer les balais, tu fais une fonction ouvrir de X degrés, et une fonction fermer de X degrés, si tu peux mettre en paramètre la vitesse de rotation c'est un plus.

L'avantage c'est que une fois que tu as le bas niveau, pour faire les réglages tu le fait en python, donc t'as pas besoin de tout recompiler sur ton arduino.

Après si tu veux tu pourra faire la fonction côté python qui ouvre, avance, referme, recul.
