### ISSUE TITLE
maitriser les ax12

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#60]
devenir maître !
il ne faut pas seulement pouvoir les bouger il faut aussi vérifier la température, le couple, etc,... bref tout ce qui renvoie -1 dans le code de Cédric xD

**Comment by apuyou** [comment]
Mais genre je suis assigné là dessus ? ^^

**Comment by trecouvr** [comment]
bah ouai t'avais plus rien à faire ^^ on go atelier aujourd'hui et on torche ça
