### ISSUE TITLE
corriger bug comptage de points

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#72]
les cds noirs sont pris en compte dans le comptage des points du simulateur

**Comment by QuentinG42** [comment]
Il faudra aussi prendre en compte le "niveau" de remplissage que
nous fournit les sharps

Quentin

2012/3/7 trecouvr <
reply@reply.github.com

**Comment by trecouvr** [comment]
ouaip c'est codé dans le simu.

2012/3/7 QuentinG42 <
reply@reply.github.com
