### ISSUE TITLE
asserv ++

### ISSUE THREAD

**Issue by trecouvr** [utcoupe/Coupe2012#8]
améliorer l'asserv

**Comment by apuyou** [comment]
Tu pourrais faire un listing précis des points à améliorer/changer ?

**Comment by mattgu74** [comment]
- Gérer l'enchainement de points (pas besoin de s'arréter entre deux points) C'EST le truc à faire en n°1
  Après il y a :
- Mieux gérer l'acceleration et le freinage (enfin faut voir comment c'est actuellement)
- Faire des déplacements curviligne...

Puis ça sera bien :)

**Comment by apuyou** [comment]
Curviligne apparemment c'est juste un réglage, il faut le faire ressortir.

Reste effectivement l'enchaînement de points et un vrai trapèze de vitesse.

Thomas réclame : désactiver le mode "biface" de l'asserv pour l'obliger à avancer tout le temps dans la même direction.

**Comment by trecouvr** [comment]
séparation en plusieurs issues.
